// Copyright (C) 2025 Zac Sweers
// SPDX-License-Identifier: Apache-2.0
package dev.zacsweers.metro.compiler.fir.generators

import dev.zacsweers.metro.compiler.asName
import dev.zacsweers.metro.compiler.compat.CompatContext
import dev.zacsweers.metro.compiler.fir.Keys
import dev.zacsweers.metro.compiler.fir.argumentAsOrNull
import dev.zacsweers.metro.compiler.fir.buildSimpleAnnotation
import dev.zacsweers.metro.compiler.fir.classIds
import dev.zacsweers.metro.compiler.fir.getAnnotationArgParamNames
import dev.zacsweers.metro.compiler.fir.hasOrigin
import dev.zacsweers.metro.compiler.fir.isKClassOfTypeParameter
import dev.zacsweers.metro.compiler.fir.isProvidesAnnotated
import dev.zacsweers.metro.compiler.fir.isResolved
import dev.zacsweers.metro.compiler.fir.markAsDeprecatedHidden
import dev.zacsweers.metro.compiler.fir.predicates
import dev.zacsweers.metro.compiler.fir.replaceAnnotationsSafe
import dev.zacsweers.metro.compiler.fir.resolvedClassId
import dev.zacsweers.metro.compiler.symbols.Symbols
import org.jetbrains.kotlin.builtins.StandardNames
import org.jetbrains.kotlin.descriptors.ClassKind
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.caches.FirCache
import org.jetbrains.kotlin.fir.caches.firCachesFactory
import org.jetbrains.kotlin.fir.declarations.DirectDeclarationsAccess
import org.jetbrains.kotlin.fir.declarations.toAnnotationClassIdSafe
import org.jetbrains.kotlin.fir.expressions.FirAnnotation
import org.jetbrains.kotlin.fir.expressions.FirCall
import org.jetbrains.kotlin.fir.expressions.FirExpression
import org.jetbrains.kotlin.fir.expressions.FirGetClassCall
import org.jetbrains.kotlin.fir.expressions.FirQualifiedAccessExpression
import org.jetbrains.kotlin.fir.expressions.builder.buildAnnotation
import org.jetbrains.kotlin.fir.expressions.builder.buildAnnotationArgumentMapping
import org.jetbrains.kotlin.fir.expressions.builder.buildArgumentList
import org.jetbrains.kotlin.fir.expressions.builder.buildGetClassCall
import org.jetbrains.kotlin.fir.expressions.builder.buildResolvedQualifier
import org.jetbrains.kotlin.fir.extensions.FirDeclarationGenerationExtension
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.extensions.MemberGenerationContext
import org.jetbrains.kotlin.fir.extensions.NestedClassGenerationContext
import org.jetbrains.kotlin.fir.plugin.createDefaultPrivateConstructor
import org.jetbrains.kotlin.fir.plugin.createNestedClass
import org.jetbrains.kotlin.fir.references.FirNamedReference
import org.jetbrains.kotlin.fir.resolve.defaultType
import org.jetbrains.kotlin.fir.resolve.providers.symbolProvider
import org.jetbrains.kotlin.fir.resolve.substitution.substitutorByMap
import org.jetbrains.kotlin.fir.symbols.impl.FirCallableSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirClassLikeSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirClassSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirConstructorSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirNamedFunctionSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.fir.toFirResolvedTypeRef
import org.jetbrains.kotlin.fir.types.ConeTypeParameterType
import org.jetbrains.kotlin.fir.types.constructClassLikeType
import org.jetbrains.kotlin.fir.types.impl.ConeClassLikeTypeImpl
import org.jetbrains.kotlin.fir.types.toLookupTag
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name
import org.jetbrains.kotlin.name.SpecialNames
import org.jetbrains.kotlin.name.StandardClassIds

/**
 * Generates nested binding container objects for classes annotated with
 * `@ContributesBindingContainer`-annotated custom annotations.
 *
 * For example, given:
 * ```kotlin
 * interface MyTemplate<T> {
 *   @Provides fun customProvides(target: T): SomeType = SomeType(target)
 * }
 *
 * @ContributesBindingContainer(MyTemplate::class)
 * annotation class CustomAnnotation(val scope: KClass<*>, val replaces: Array<KClass<*>> = [])
 *
 * @CustomAnnotation(AppScope::class)
 * class TargetClass @Inject constructor()
 * ```
 *
 * This generates:
 * ```kotlin
 * @ContributesTo(AppScope::class)
 * @BindingContainer
 * @Origin(TargetClass::class)
 * object MetroBindingContainerForMyTemplate : MyTemplate<TargetClass>
 * ```
 *
 * Factory classes for the template's @Provides functions are generated by
 * [ProvidesFactoryFirGenerator], which discovers them from the binding container's template
 * interface supertypes.
 */
internal class BindingContainerObjectFirGenerator(
  session: FirSession,
  compatContext: CompatContext,
) : FirDeclarationGenerationExtension(session), CompatContext by compatContext {

  private data class BindingContainerInfo(
    val generatedName: Name,
    val templateInterfaceClassId: ClassId,
    val annotationClassId: ClassId,
    val scopeArg: FirGetClassCall,
    val replacesArg: FirExpression?,
  )

  private val classToBindingContainers:
    FirCache<FirClassSymbol<*>, List<BindingContainerInfo>, Unit> =
    session.firCachesFactory.createCache { classSymbol, _ ->
      val classIds = session.classIds
      buildList {
        for (annotation in classSymbol.resolvedCompilerAnnotationsWithClassIds) {
          if (!annotation.isResolved) continue
          val annotationClassId = annotation.toAnnotationClassIdSafe(session) ?: continue

          val annotationClassSymbol =
            session.symbolProvider.getClassLikeSymbolByClassId(annotationClassId)
              as? FirRegularClassSymbol ?: continue

          val metaAnnotation =
            annotationClassSymbol.resolvedCompilerAnnotationsWithClassIds.firstOrNull {
              it.isResolved &&
                it.toAnnotationClassIdSafe(session) ==
                  classIds.contributesBindingContainerAnnotation
            } ?: continue

          val templateInterfaceClassId =
            extractTemplateClassId(metaAnnotation, annotationClassId) ?: continue

          // Fall back to defaultScope from the meta-annotation
          val scopeArg =
            extractScopeArg(annotation)
              ?: extractDefaultScopeArg(metaAnnotation, annotationClassId)
              ?: continue

          val replacesArg = extractReplacesArg(annotation)

          val generatedName =
            (Symbols.StringNames.METRO_BINDING_CONTAINER_FOR_PREFIX +
                templateInterfaceClassId.shortClassName.identifier)
              .asName()

          add(
            BindingContainerInfo(
              generatedName,
              templateInterfaceClassId,
              annotationClassId,
              scopeArg,
              replacesArg,
            )
          )
        }
      }
    }

  private data class BindingContainerImplInfo(
    val templateInterfaceClassId: ClassId,
    val targetClassId: ClassId,
    val annotationClassId: ClassId,
    val implFunctions: Map<Name, Name>,
    val scopeArg: FirGetClassCall,
  )

  private val bindingContainerClassIdToImplInfo = mutableMapOf<ClassId, BindingContainerImplInfo>()

  override fun FirDeclarationPredicateRegistrar.registerPredicates() {
    register(session.predicates.contributesBindingContainerPredicate)
  }

  override fun getNestedClassifiersNames(
    classSymbol: FirClassSymbol<*>,
    context: NestedClassGenerationContext,
  ): Set<Name> {
    val result = mutableSetOf<Name>()

    for (info in classToBindingContainers.getValue(classSymbol, Unit)) {
      result.add(info.generatedName)

      val bindingContainerClassId = classSymbol.classId.createNestedClassId(info.generatedName)
      val implFunctions = getImplFunctionEntries(info.templateInterfaceClassId)
      bindingContainerClassIdToImplInfo[bindingContainerClassId] =
        BindingContainerImplInfo(
          templateInterfaceClassId = info.templateInterfaceClassId,
          targetClassId = classSymbol.classId,
          annotationClassId = info.annotationClassId,
          implFunctions = implFunctions,
          scopeArg = info.scopeArg,
        )
    }

    return result
  }

  @OptIn(DirectDeclarationsAccess::class)
  private fun getImplFunctionEntries(templateInterfaceClassId: ClassId): Map<Name, Name> {
    val templateSymbol =
      session.symbolProvider.getClassLikeSymbolByClassId(templateInterfaceClassId)
        as? FirRegularClassSymbol ?: return emptyMap()
    return templateSymbol.declarationSymbols
      .filterIsInstance<FirCallableSymbol<*>>()
      .filter { it.isProvidesAnnotated(session, session.classIds.providesAnnotations) }
      .associate { (it.name.identifier + Symbols.StringNames.IMPL_SUFFIX).asName() to it.name }
  }

  override fun getCallableNamesForClass(
    classSymbol: FirClassSymbol<*>,
    context: MemberGenerationContext,
  ): Set<Name> {
    if (
      !classSymbol.name.isSpecial &&
        classSymbol.name.identifier.startsWith(
          Symbols.StringNames.METRO_BINDING_CONTAINER_FOR_PREFIX
        ) &&
        classSymbol.hasOrigin(Keys.BindingContainerObjectDeclaration)
    ) {
      val implInfo = bindingContainerClassIdToImplInfo[classSymbol.classId]
      return buildSet {
        add(SpecialNames.INIT)
        implInfo?.implFunctions?.keys?.let(::addAll)
      }
    }

    return emptySet()
  }

  override fun generateConstructors(context: MemberGenerationContext): List<FirConstructorSymbol> {
    if (
      !context.owner.name.isSpecial &&
        context.owner.name.identifier.startsWith(
          Symbols.StringNames.METRO_BINDING_CONTAINER_FOR_PREFIX
        ) &&
        context.owner.hasOrigin(Keys.BindingContainerObjectDeclaration)
    ) {
      return listOf(
        createDefaultPrivateConstructor(context.owner, Keys.BindingContainerObjectDeclaration)
          .symbol
      )
    }

    return emptyList()
  }

  override fun generateNestedClassLikeDeclaration(
    owner: FirClassSymbol<*>,
    name: Name,
    context: NestedClassGenerationContext,
  ): FirClassLikeSymbol<*>? {
    if (
      name.isSpecial ||
        !name.identifier.startsWith(Symbols.StringNames.METRO_BINDING_CONTAINER_FOR_PREFIX)
    )
      return null
    val infos = classToBindingContainers.getValue(owner, Unit)
    val info = infos.find { it.generatedName == name } ?: return null

    val targetClassType = owner.defaultType()
    val supertypeWithTypeArg =
      info.templateInterfaceClassId.constructClassLikeType(arrayOf(targetClassType))

    return createNestedClass(
        owner,
        name = name,
        key = Keys.BindingContainerObjectDeclaration,
        classKind = ClassKind.OBJECT,
      ) {
        superType(supertypeWithTypeArg)
      }
      .apply {
        markAsDeprecatedHidden(session)

        val annotations = buildList {
          add(buildContributesToAnnotation(info.scopeArg, info.replacesArg))
          add(buildBindingContainerAnnotation())
          add(buildOriginAnnotation(owner.classId))
        }

        replaceAnnotations(this@apply.annotations + annotations)
      }
      .symbol
  }

  override fun generateFunctions(
    callableId: CallableId,
    context: MemberGenerationContext?,
  ): List<FirNamedFunctionSymbol> {
    val nonNullContext = context ?: return emptyList()
    if (callableId.callableName == SpecialNames.INIT) return emptyList()

    val implInfo =
      bindingContainerClassIdToImplInfo[nonNullContext.owner.classId] ?: return emptyList()

    if (callableId.callableName !in implInfo.implFunctions) return emptyList()

    if (nonNullContext.owner.hasOrigin(Keys.BindingContainerObjectDeclaration)) {
      return generateImplFunction(callableId, nonNullContext, implInfo)
    }

    return emptyList()
  }

  @OptIn(DirectDeclarationsAccess::class)
  private fun generateImplFunction(
    callableId: CallableId,
    context: MemberGenerationContext,
    info: BindingContainerImplInfo,
  ): List<FirNamedFunctionSymbol> {
    val originalName = info.implFunctions[callableId.callableName] ?: return emptyList()

    val templateSymbol =
      session.symbolProvider.getClassLikeSymbolByClassId(info.templateInterfaceClassId)
        as? FirRegularClassSymbol ?: return emptyList()

    val providesFunction =
      templateSymbol.declarationSymbols.filterIsInstance<FirNamedFunctionSymbol>().firstOrNull {
        it.name == originalName
      } ?: return emptyList()

    val targetClassSymbol =
      session.symbolProvider.getClassLikeSymbolByClassId(info.targetClassId)
        as? FirRegularClassSymbol ?: return emptyList()
    val targetClassType = targetClassSymbol.defaultType()
    val substitutionMap = templateSymbol.typeParameterSymbols.zip(listOf(targetClassType)).toMap()
    val substitutor = substitutorByMap(substitutionMap, session)

    val returnType = substitutor.substituteOrSelf(providesFunction.resolvedReturnType)

    // Skip KClass<T> params (always compiler-provided), T-typed params for object targets,
    // and params matching custom annotation constructor args
    val isTargetObject = targetClassSymbol.classKind == ClassKind.OBJECT
    val annotationClassSymbol =
      session.symbolProvider.getClassLikeSymbolByClassId(info.annotationClassId)
        as? FirRegularClassSymbol
    val annotationArgParamNames =
      annotationClassSymbol?.let { getAnnotationArgParamNames(it, session) } ?: emptySet()
    val keptParams =
      providesFunction.valueParameterSymbols.filter { param ->
        val type = param.resolvedReturnType
        !isKClassOfTypeParameter(type) &&
          !(isTargetObject && type is ConeTypeParameterType) &&
          param.name !in annotationArgParamNames
      }

    val function =
      createMemberFunction(
          context.owner,
          Keys.BindingContainerImplFunction,
          callableId.callableName,
          returnType = returnType,
        ) {
          for (param in keptParams) {
            val substitutedType = substitutor.substituteOrSelf(param.resolvedReturnType)
            valueParameter(name = param.name, key = Keys.RegularParameter, type = substitutedType)
          }
        }
        .apply {
          val templateAnnotations =
            substituteTemplateScopeInAnnotations(
              providesFunction.resolvedCompilerAnnotationsWithClassIds.toList(),
              info.scopeArg,
            )
          replaceAnnotationsSafe(annotations + templateAnnotations)
          for ((i, param) in keptParams.withIndex()) {
            if (i < valueParameters.size) {
              valueParameters[i].replaceAnnotationsSafe(
                param.resolvedCompilerAnnotationsWithClassIds
              )
            }
          }
        }
        .symbol as FirNamedFunctionSymbol

    return listOf(function)
  }

  private fun substituteTemplateScopeInAnnotations(
    annotations: List<FirAnnotation>,
    scopeArg: FirGetClassCall,
  ): List<FirAnnotation> {
    return annotations.map { annotation ->
      val mapping = annotation.argumentMapping.mapping
      val needsSubstitution = mapping.values.any { it is FirGetClassCall && it.isTemplateScope() }
      if (!needsSubstitution) {
        annotation
      } else {
        buildAnnotation {
          annotationTypeRef = annotation.annotationTypeRef
          argumentMapping = buildAnnotationArgumentMapping {
            for ((name, value) in mapping) {
              if (value is FirGetClassCall && value.isTemplateScope()) {
                this.mapping[name] = scopeArg
              } else {
                this.mapping[name] = value
              }
            }
          }
        }
      }
    }
  }

  private fun FirGetClassCall.isTemplateScope(): Boolean {
    resolvedClassId()?.let {
      return it == Symbols.ClassIds.metroTemplateScope
    }
    val ref =
      (argument as? FirQualifiedAccessExpression)
        ?.calleeReference
        ?.let { it as? FirNamedReference }
        ?.name
    return ref?.identifier == Symbols.StringNames.TEMPLATE_SCOPE
  }

  private fun extractTemplateClassId(
    metaAnnotation: FirAnnotation,
    annotationClassId: ClassId,
  ): ClassId? {
    val getClassCall =
      metaAnnotation.argumentAsOrNull<FirGetClassCall>(Symbols.Names.template, 0)
        ?: return null
    return resolveClassReference(getClassCall, annotationClassId)?.first
  }

  private fun extractScopeArg(annotation: FirAnnotation): FirGetClassCall? {
    return annotation.argumentAsOrNull<FirGetClassCall>(Symbols.Names.scope, 0)
  }

  /** Returns null if not set (Nothing::class sentinel). */
  private fun extractDefaultScopeArg(
    metaAnnotation: FirAnnotation,
    annotationClassId: ClassId,
  ): FirGetClassCall? {
    val getClassCall =
      metaAnnotation.argumentAsOrNull<FirGetClassCall>(Symbols.Names.defaultScope, 1) ?: return null

    val resolvedClassId = getClassCall.resolvedClassId()
    if (resolvedClassId != null) {
      if (resolvedClassId == StandardClassIds.Nothing) return null
      return getClassCall
    }

    val (classId, symbol) = resolveClassReference(getClassCall, annotationClassId) ?: return null
    return buildResolvedGetClassCall(classId, symbol)
  }

  /**
   * Resolves a [FirGetClassCall] to a [ClassId] and [FirRegularClassSymbol] pair. Falls back to
   * candidate package resolution during COMPANION_GENERATION phase when annotation arguments may
   * not be fully resolved yet.
   */
  private fun resolveClassReference(
    getClassCall: FirGetClassCall,
    annotationClassId: ClassId,
  ): Pair<ClassId, FirRegularClassSymbol>? {
    getClassCall.resolvedClassId()?.let { classId ->
      val symbol =
        session.symbolProvider.getClassLikeSymbolByClassId(classId) as? FirRegularClassSymbol
          ?: return null
      return classId to symbol
    }

    val simpleName =
      (getClassCall.argument as? FirQualifiedAccessExpression)
        ?.calleeReference
        ?.let { it as? FirNamedReference }
        ?.name ?: return null

    val candidatePackages =
      listOf(annotationClassId.packageFqName, FqName.ROOT, Symbols.FqNames.metroRuntimePackage)
    for (pkg in candidatePackages.distinct()) {
      val candidateClassId = ClassId(pkg, simpleName)
      val symbol =
        session.symbolProvider.getClassLikeSymbolByClassId(candidateClassId)
          as? FirRegularClassSymbol ?: continue
      return candidateClassId to symbol
    }

    return null
  }

  private fun extractReplacesArg(annotation: FirAnnotation): FirExpression? {
    val arg = annotation.argumentAsOrNull<FirExpression>(Symbols.Names.replaces, 1) ?: return null
    // Skip empty array literals (default values) — they don't need propagation since
    // @ContributesTo already defaults to []. Copying unresolved FirArrayLiteralImpl
    // causes Fir2Ir failures because the expression has no resolved type set.
    if (arg is FirCall && arg.argumentList.arguments.isEmpty()) return null
    return arg
  }

  private fun buildResolvedGetClassCall(
    classId: ClassId,
    symbol: FirRegularClassSymbol,
  ): FirGetClassCall {
    val classType = symbol.defaultType()
    return buildGetClassCall {
      argumentList = buildArgumentList {
        arguments += buildResolvedQualifier {
          packageFqName = classId.packageFqName
          relativeClassFqName = classId.relativeClassName
          this.symbol = symbol
          resolvedToCompanionObject = false
          isFullyQualified = true
          coneTypeOrNull = classType
        }
      }
      coneTypeOrNull =
        ConeClassLikeTypeImpl(
          StandardClassIds.KClass.toLookupTag(),
          arrayOf(classType),
          isMarkedNullable = false,
        )
    }
  }

  private fun buildContributesToAnnotation(
    scopeArg: FirGetClassCall,
    replacesArg: FirExpression?,
  ): FirAnnotation {
    val contributesToClassId = session.classIds.contributesToAnnotations.first()
    val contributesToSymbol =
      session.symbolProvider.getClassLikeSymbolByClassId(contributesToClassId)
        as FirRegularClassSymbol
    return buildAnnotation {
      annotationTypeRef = contributesToSymbol.defaultType().toFirResolvedTypeRef()
      argumentMapping = buildAnnotationArgumentMapping {
        mapping[Symbols.Names.scope] = scopeArg
        if (replacesArg != null) {
          mapping[Symbols.Names.replaces] = replacesArg
        }
      }
    }
  }

  private fun buildBindingContainerAnnotation(): FirAnnotation {
    val bindingContainerClassId = session.classIds.bindingContainerAnnotations.first()
    val bindingContainerSymbol =
      session.symbolProvider.getClassLikeSymbolByClassId(bindingContainerClassId)
        as FirRegularClassSymbol
    return buildSimpleAnnotation { bindingContainerSymbol }
  }

  private fun buildOriginAnnotation(targetClassId: ClassId): FirAnnotation {
    val originSymbol =
      session.symbolProvider.getClassLikeSymbolByClassId(Symbols.ClassIds.metroOrigin)
        as FirRegularClassSymbol

    val targetSymbol =
      session.symbolProvider.getClassLikeSymbolByClassId(targetClassId) as? FirRegularClassSymbol
        ?: error("Could not find target class: $targetClassId")

    return buildAnnotation {
      annotationTypeRef = originSymbol.defaultType().toFirResolvedTypeRef()
      argumentMapping = buildAnnotationArgumentMapping {
        mapping[StandardNames.DEFAULT_VALUE_PARAMETER] =
          buildResolvedGetClassCall(targetClassId, targetSymbol)
      }
    }
  }
}
